name: Verify Time and Price Before Closing

on:
  issues:
    types: [closed]

jobs:
  check_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pyairtable==3.0.2

      - name: Run Issue Check Script
        env:
          GITHUB_TOKEN: ${{ secrets.EQUISTAMP_ADMIN_GITHUB_SECRET }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
          TASK_TO_AIRTABLE_STATUS: ${{ vars.TASK_TO_AIRTABLE_STATUS }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python .github/scripts/verify_closed_issue.py
      
      - name: Comment with Successes
        run: |
          SUCCESS_MESSAGE=$(cat success_messages.txt)
          gh issue comment ${{ github.event.issue.number }} --body "$SUCCESS_MESSAGE"
        env:
          GH_TOKEN: ${{ secrets.EQUISTAMP_ADMIN_GITHUB_SECRET }}

      - name: Comment with Failures and Reopen
        if: failure()
        run: |
          ERROR_MESSAGE=$(cat error_messages.txt)
          SUCCESS_MESSAGE=$(cat success_messages.txt)
          echo -e "$ERROR_MESSAGE\n\n$SUCCESS_MESSAGE" | gh issue comment ${{ github.event.issue.number }} --body-file -
          gh issue reopen ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.EQUISTAMP_ADMIN_GITHUB_SECRET }}
